name:                AdventOfCode2022
version:             0.1.0.0
github:              "SebTee/AdventOfCode2022"
license:             MIT
author:              "Sebastian Tee"
maintainer:          "Sebastian Tee"
copyright:           "2022 Sebastian Tee"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/SebTee/AdventOfCode2022#readme>

dependencies:
- base >= 4.7 && < 5
- split
- groupBy
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  AdventOfCode2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2022
